import type { MiniQuestion, Question, World, WorldId } from "@/types/types";

export const AVATARS = [
	"🦊",
	"🐼",
	"🐱",
	"🐲",
	"👦",
	"👧",
	"🤖",
	"🧙‍♂️",
] as const;

/** Minimum percentage to pass a level and unlock the next world. */
export const PASS_THRESHOLD = 70;
/** Bonus XP for a flawless run. */
export const PERFECT_BONUS = 25;
/** Bonus XP for answering quickly. */
export const FAST_BONUS = 5;
/** Seconds remaining at/above which the fast bonus applies. */
export const FAST_BONUS_THRESHOLD = 20;

export const WORLDS: Record<WorldId, World> = {
	1: {
		id: 1,
		name: "Bilangan Berpangkat",
		emoji: "🚀",
		subtitle: "Pangkat Bulat",
		accent: "sky",
		lesson:
			"Bilangan berpangkat adalah perkalian berulang dari bilangan yang sama.",
		concept:
			"Bentuk umum: aⁿ = a × a × … × a (sebanyak n faktor).\n\nSifat penting:\n• aᵐ × aⁿ = aᵐ⁺ⁿ\n• aᵐ ÷ aⁿ = aᵐ⁻ⁿ\n• (aᵐ)ⁿ = aᵐⁿ\n• a⁰ = 1 (untuk a ≠ 0)\n• a⁻ⁿ = 1 / aⁿ",
		formula: "aᵐ × aⁿ = aᵐ⁺ⁿ",
		example: "3² × 3³ = 3⁵ = 243",
	},
	2: {
		id: 2,
		name: "Bentuk Akar",
		emoji: "💎",
		subtitle: "Akar & Operasinya",
		accent: "emerald",
		lesson:
			"Akar adalah kebalikan dari pangkat. Banyak bentuk akar merupakan bilangan irasional.",
		concept:
			"Sifat penting:\n• √(a × b) = √a × √b\n• √(a / b) = √a / √b\n• a√c + b√c = (a + b)√c\n• a√c − b√c = (a − b)√c",
		formula: "√a × √b = √(a × b)",
		example: "√12 = √(4 × 3) = 2√3",
	},
	3: {
		id: 3,
		name: "Bentuk Baku",
		emoji: "🔬",
		subtitle: "Notasi Ilmiah",
		accent: "violet",
		lesson:
			"Bentuk baku (notasi ilmiah) menulis angka sangat besar atau sangat kecil sebagai a × 10ⁿ.",
		concept:
			"Bentuk umum: a × 10ⁿ dengan syarat 1 ≤ a < 10 dan n bilangan bulat.\n\nContoh:\n• 2.500.000 = 2,5 × 10⁶\n• 0,00045 = 4,5 × 10⁻⁴",
		formula: "a × 10ⁿ, dengan 1 ≤ a < 10",
		example: "4500 = 4,5 × 10³",
	},
};

export const QUESTION_BANK: Record<WorldId, Question[]> = {
	1: [
		{
			id: "w1q1",
			prompt: "Bentuk sederhana dari 2³ adalah …",
			type: "mc",
			options: ["2 × 3", "2 + 2 + 2", "2 × 2 × 2", "3 × 3"],
			answer: "2 × 2 × 2",
			difficulty: "mudah",
			xp: 10,
			explanation:
				"2³ artinya angka 2 dikalikan dirinya sendiri sebanyak 3 kali (2 × 2 × 2).",
		},
		{
			id: "w1q2",
			prompt: "Berapakah hasil dari 5²?",
			type: "mc",
			options: ["10", "20", "25", "52"],
			answer: "25",
			difficulty: "mudah",
			xp: 10,
			explanation: "5² = 5 × 5 = 25.",
		},
		{
			id: "w1q3",
			prompt: "Berapakah nilai dari 100⁰?",
			type: "mc",
			options: ["100", "0", "1", "10"],
			answer: "1",
			difficulty: "mudah",
			xp: 10,
			explanation: "Setiap bilangan bukan nol berpangkat 0 hasilnya 1.",
		},
		{
			id: "w1q4",
			prompt: "Sifat perkalian pangkat: 3² × 3⁴ = …",
			type: "mc",
			options: ["3⁸", "3⁶", "9⁶", "9⁸"],
			answer: "3⁶",
			difficulty: "mudah",
			xp: 10,
			explanation: "Basis sama dikali → pangkat dijumlahkan: 3²⁺⁴ = 3⁶.",
		},
		{
			id: "w1q5",
			prompt: "Hasil dari 2⁵ ÷ 2² adalah …",
			type: "mc",
			options: ["2⁷", "2³", "4³", "1³"],
			answer: "2³",
			difficulty: "sedang",
			xp: 20,
			explanation: "Basis sama dibagi → pangkat dikurangkan: 2⁵⁻² = 2³.",
		},
		{
			id: "w1q6",
			prompt: "Bentuk sederhana dari (2³)⁴ adalah …",
			type: "mc",
			options: ["2⁷", "2¹²", "6⁴", "8⁴"],
			answer: "2¹²",
			difficulty: "sedang",
			xp: 20,
			explanation: "Pangkat dari pangkat → dikalikan: 2³ˣ⁴ = 2¹².",
		},
		{
			id: "w1q7",
			prompt: "Nilai dari 2⁻³ adalah …",
			type: "mc",
			options: ["−6", "−8", "1/6", "1/8"],
			answer: "1/8",
			difficulty: "sedang",
			xp: 20,
			explanation: "Pangkat negatif jadi kebalikan: 2⁻³ = 1/2³ = 1/8.",
		},
		{
			id: "w1q8",
			prompt: "Berapakah hasil dari 3² + 2³?",
			type: "mc",
			options: ["17", "15", "12", "72"],
			answer: "17",
			difficulty: "sedang",
			xp: 20,
			explanation: "3² = 9 dan 2³ = 8, jadi 9 + 8 = 17.",
		},
		{
			id: "w1q9",
			prompt: "HOTS — Jika 2ˣ = 32, berapakah nilai x?",
			type: "mc",
			options: ["4", "5", "6", "16"],
			answer: "5",
			difficulty: "sulit",
			xp: 30,
			explanation: "2 × 2 × 2 × 2 × 2 = 32, jadi 2⁵ = 32 dan x = 5.",
		},
		{
			id: "w1q10",
			prompt: "HOTS — Bentuk paling sederhana dari (4² × 2³) ÷ 2⁴ adalah …",
			type: "mc",
			options: ["2³", "2⁴", "2⁵", "2⁶"],
			answer: "2³",
			difficulty: "sulit",
			xp: 30,
			explanation: "4² = 2⁴, jadi (2⁴ × 2³) ÷ 2⁴ = 2⁷ ÷ 2⁴ = 2³.",
		},
	],
	2: [
		{
			id: "w2q1",
			prompt: "Berapakah hasil dari √36?",
			type: "mc",
			options: ["4", "6", "8", "18"],
			answer: "6",
			difficulty: "mudah",
			xp: 10,
			explanation: "6 × 6 = 36, jadi √36 = 6.",
		},
		{
			id: "w2q2",
			prompt: "Hasil dari √100 adalah …",
			type: "mc",
			options: ["10", "50", "100", "200"],
			answer: "10",
			difficulty: "mudah",
			xp: 10,
			explanation: "10 × 10 = 100, jadi √100 = 10.",
		},
		{
			id: "w2q3",
			prompt: "Bentuk lain dari √a × √b adalah …",
			type: "mc",
			options: ["√(a+b)", "√(a−b)", "√(a×b)", "√(a/b)"],
			answer: "√(a×b)",
			difficulty: "mudah",
			xp: 10,
			explanation: "Sifat akar: √a × √b = √(a × b).",
		},
		{
			id: "w2q4",
			prompt: "Berapakah hasil dari 3√5 + 2√5?",
			type: "mc",
			options: ["5√5", "6√5", "5√10", "6√10"],
			answer: "5√5",
			difficulty: "mudah",
			xp: 10,
			explanation: "Akar sejenis → jumlahkan koefisien: (3+2)√5 = 5√5.",
		},
		{
			id: "w2q5",
			prompt: "Bentuk sederhana dari √12 adalah …",
			type: "mc",
			options: ["2√3", "3√2", "4√3", "2√6"],
			answer: "2√3",
			difficulty: "sedang",
			xp: 20,
			explanation: "√12 = √(4 × 3) = √4 × √3 = 2√3.",
		},
		{
			id: "w2q6",
			prompt: "Hasil perkalian √3 × √12 adalah …",
			type: "mc",
			options: ["√15", "6", "18", "36"],
			answer: "6",
			difficulty: "sedang",
			xp: 20,
			explanation: "√3 × √12 = √36 = 6.",
		},
		{
			id: "w2q7",
			prompt: "Berapakah nilai dari √48 ÷ √3?",
			type: "mc",
			options: ["√45", "√15", "4", "16"],
			answer: "4",
			difficulty: "sedang",
			xp: 20,
			explanation: "√48 ÷ √3 = √(48/3) = √16 = 4.",
		},
		{
			id: "w2q8",
			prompt: "Bentuk sederhana dari √8 + √18 adalah …",
			type: "mc",
			options: ["√26", "2√26", "5√2", "6√2"],
			answer: "5√2",
			difficulty: "sedang",
			xp: 20,
			explanation: "√8 = 2√2 dan √18 = 3√2, jadi 2√2 + 3√2 = 5√2.",
		},
		{
			id: "w2q9",
			prompt: "HOTS — Luas sebuah persegi 50 cm². Panjang sisinya?",
			type: "mc",
			options: ["5 cm", "10 cm", "5√2 cm", "25 cm"],
			answer: "5√2 cm",
			difficulty: "sulit",
			xp: 30,
			explanation: "Sisi = √Luas = √50 = √(25 × 2) = 5√2 cm.",
		},
		{
			id: "w2q10",
			prompt: "HOTS — Jika x = √2 dan y = √8, berapakah x × y + x²?",
			type: "mc",
			options: ["6", "8", "10", "16"],
			answer: "6",
			difficulty: "sulit",
			xp: 30,
			explanation: "x × y = √16 = 4 dan x² = 2, jadi 4 + 2 = 6.",
		},
	],
	3: [
		{
			id: "w3q1",
			prompt: "Syarat nilai a pada bentuk baku a × 10ⁿ adalah …",
			type: "mc",
			options: ["a < 1", "1 ≤ a < 10", "a > 10", "a bilangan bulat"],
			answer: "1 ≤ a < 10",
			difficulty: "mudah",
			xp: 10,
			explanation: "Nilai a harus dari 1 sampai kurang dari 10.",
		},
		{
			id: "w3q2",
			prompt: "Bentuk baku dari 3.000 adalah …",
			type: "mc",
			options: ["3 × 10²", "3 × 10³", "30 × 10²", "0,3 × 10⁴"],
			answer: "3 × 10³",
			difficulty: "mudah",
			xp: 10,
			explanation: "3.000 = 3 × 1.000 = 3 × 10³.",
		},
		{
			id: "w3q3",
			prompt: "Bentuk baku dari 0,005 adalah …",
			type: "mc",
			options: ["5 × 10³", "5 × 10⁻³", "0,5 × 10⁻²", "50 × 10⁻⁴"],
			answer: "5 × 10⁻³",
			difficulty: "mudah",
			xp: 10,
			explanation: "Koma digeser 3 langkah ke kanan → pangkat −3.",
		},
		{
			id: "w3q4",
			prompt: "Bilangan 4,2 × 10⁴ sama dengan …",
			type: "mc",
			options: ["4.200", "42.000", "420.000", "0,00042"],
			answer: "42.000",
			difficulty: "mudah",
			xp: 10,
			explanation: "4,2 × 10.000 = 42.000.",
		},
		{
			id: "w3q5",
			prompt: "Bentuk baku dari 125.000.000 adalah …",
			type: "mc",
			options: ["12,5 × 10⁷", "1,25 × 10⁸", "1,25 × 10⁷", "125 × 10⁶"],
			answer: "1,25 × 10⁸",
			difficulty: "sedang",
			xp: 20,
			explanation: "1,25 dengan koma mundur 8 langkah → 1,25 × 10⁸.",
		},
		{
			id: "w3q6",
			prompt: "Bentuk baku dari 0,0000078 adalah …",
			type: "mc",
			options: ["7,8 × 10⁻⁶", "7,8 × 10⁻⁷", "78 × 10⁻⁷", "7,8 × 10⁶"],
			answer: "7,8 × 10⁻⁶",
			difficulty: "sedang",
			xp: 20,
			explanation: "Koma digeser 6 langkah ke kanan → 7,8 × 10⁻⁶.",
		},
		{
			id: "w3q7",
			prompt: "Hasil dari (2 × 10³) × (3 × 10⁴) adalah …",
			type: "mc",
			options: ["5 × 10⁷", "6 × 10⁷", "6 × 10¹²", "5 × 10¹²"],
			answer: "6 × 10⁷",
			difficulty: "sedang",
			xp: 20,
			explanation: "(2 × 3) × (10³ × 10⁴) = 6 × 10⁷.",
		},
		{
			id: "w3q8",
			prompt: "Hasil dari (8 × 10⁵) ÷ (2 × 10²) adalah …",
			type: "mc",
			options: ["4 × 10³", "4 × 10⁷", "6 × 10³", "16 × 10³"],
			answer: "4 × 10³",
			difficulty: "sedang",
			xp: 20,
			explanation: "(8 ÷ 2) × 10⁵⁻² = 4 × 10³.",
		},
		{
			id: "w3q9",
			prompt:
				"HOTS — Jarak ke matahari 150.000.000 km, cahaya 3 × 10⁵ km/detik. Lama cahaya sampai?",
			type: "mc",
			options: ["500 detik", "50 detik", "5 × 10³ detik", "5 detik"],
			answer: "500 detik",
			difficulty: "sulit",
			xp: 30,
			explanation: "Waktu = (1,5 × 10⁸) ÷ (3 × 10⁵) = 0,5 × 10³ = 500 detik.",
		},
		{
			id: "w3q10",
			prompt: "HOTS — Bentuk baku dari 450 × 10⁻⁵ adalah …",
			type: "mc",
			options: ["4,5 × 10⁻³", "4,5 × 10⁻⁷", "4,5 × 10⁻²", "45 × 10⁻⁴"],
			answer: "4,5 × 10⁻³",
			difficulty: "sulit",
			xp: 30,
			explanation: "450 = 4,5 × 10², jadi 4,5 × 10² × 10⁻⁵ = 4,5 × 10⁻³.",
		},
	],
};

export const MINI_BY_WORLD: Record<WorldId, MiniQuestion[]> = {
	1: [
		{
			prompt: "aᵐ × aⁿ sama dengan …",
			answer: "aᵐ⁺ⁿ",
			options: ["aᵐ⁺ⁿ", "aᵐ⁻ⁿ", "aᵐⁿ"],
		},
		{
			prompt: "aᵐ ÷ aⁿ sama dengan …",
			answer: "aᵐ⁻ⁿ",
			options: ["aᵐ⁺ⁿ", "aᵐ⁻ⁿ", "aⁿ⁻ᵐ"],
		},
		{
			prompt: "(aᵐ)ⁿ sama dengan …",
			answer: "aᵐⁿ",
			options: ["aᵐ⁺ⁿ", "aᵐⁿ", "aᵐ⁻ⁿ"],
		},
		{
			prompt: "a⁰ (a ≠ 0) sama dengan …",
			answer: "1",
			options: ["0", "1", "a"],
		},
		{
			prompt: "a⁻ⁿ sama dengan …",
			answer: "1/aⁿ",
			options: ["aⁿ", "−aⁿ", "1/aⁿ"],
		},
		{ prompt: "2³ sama dengan …", answer: "8", options: ["6", "8", "9"] },
	],
	2: [
		{
			prompt: "√a × √b sama dengan …",
			answer: "√(ab)",
			options: ["√(a+b)", "√(ab)", "a√b"],
		},
		{
			prompt: "√a ÷ √b sama dengan …",
			answer: "√(a/b)",
			options: ["√(a−b)", "√(a/b)", "√a/b"],
		},
		{ prompt: "√49 sama dengan …", answer: "7", options: ["6", "7", "8"] },
		{ prompt: "√12 = … √3", answer: "2", options: ["2", "3", "4"] },
		{
			prompt: "√a × √a sama dengan …",
			answer: "a",
			options: ["a", "√a", "a²"],
		},
		{
			prompt: "2√5 + 3√5 sama dengan …",
			answer: "5√5",
			options: ["5√5", "6√5", "5√10"],
		},
	],
	3: [
		{
			prompt: "Bentuk baku berbentuk …",
			answer: "a × 10ⁿ",
			options: ["a × 10ⁿ", "10 × aⁿ", "a + 10ⁿ"],
		},
		{
			prompt: "Pada a × 10ⁿ, nilai a harus …",
			answer: "1 ≤ a < 10",
			options: ["0 < a < 1", "1 ≤ a < 10", "a > 10"],
		},
		{
			prompt: "Angka < 1 → pangkat 10 …",
			answer: "negatif",
			options: ["positif", "nol", "negatif"],
		},
		{
			prompt: "3.000 = …",
			answer: "3 × 10³",
			options: ["3 × 10²", "3 × 10³", "30 × 10²"],
		},
		{
			prompt: "7 × 10² sama dengan …",
			answer: "700",
			options: ["70", "700", "7000"],
		},
		{
			prompt: "Angka > 10 → pangkat 10 …",
			answer: "positif",
			options: ["positif", "nol", "negatif"],
		},
	],
};

export function getWorld(id: WorldId): World {
	return WORLDS[id];
}

export function getQuestions(id: WorldId): Question[] {
	return QUESTION_BANK[id];
}
